In [1]:
import pandas as pd
import xml.etree.ElementTree as xet

In [2]:
from glob import glob

In [21]:
path = glob("./imgs/*.xml")
# path

In [22]:
labels_dict = dict(filepath=[], xmin=[], xmax=[], ymin=[], ymax=[])
for filename in path:
    filename = path[0]
    info = xet.parse(filename)
    root = info.getroot()
    member_object = root.find('object')
    labels_info = member_object.find('bndbox')
    xmin = int(labels_info.find('xmin').text)
    ymin = int(labels_info.find('ymin').text)
    xmax = int(labels_info.find('xmax').text)
    ymax = int(labels_info.find('ymax').text)
    # print(xmin, ymin, xmax, ymax, filename)
    labels_dict['filepath'].append(filename)
    labels_dict['xmin'].append(xmin)
    labels_dict['ymin'].append(ymin)
    labels_dict['xmax'].append(xmax)
    labels_dict['ymax'].append(ymax)

In [24]:
df = pd.DataFrame(labels_dict)
df

           filepath  xmin  xmax  ymin  ymax
0    ./imgs/N68.xml   319   479   262   295
1    ./imgs/N68.xml   319   479   262   295
2    ./imgs/N68.xml   319   479   262   295
3    ./imgs/N68.xml   319   479   262   295
4    ./imgs/N68.xml   319   479   262   295
..              ...   ...   ...   ...   ...
220  ./imgs/N68.xml   319   479   262   295
221  ./imgs/N68.xml   319   479   262   295
222  ./imgs/N68.xml   319   479   262   295
223  ./imgs/N68.xml   319   479   262   295
224  ./imgs/N68.xml   319   479   262   295

[225 rows x 5 columns]

In [ ]:
df.to_csv